version: "3"

services:
  app:
    build: ./node
    restart: always
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    container_name: api
    volumes:
      - /usr/src/app
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    tty: true
    ports:
      - "80:80"
    depends_on:
      - app
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
